name: Add Github Release Tag

on:
  push:
    tags:
      - v*

jobs:
  release:
    if: github.repository == 'pengzhanbo/vite-plugin-image-placeholder'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create release for tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/pengzhanbo/vite-plugin-image-placeholder/blob/${{ github.ref_name }}/CHANGELOG.md) for details.

